# Generated by Django 5.1.3 on 2024-11-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
