# Generated by Django 5.1.3 on 2024-11-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dmsuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
    ]
